// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/proto/nebulapb/vector_service.proto

package nebulapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Values        []float32              `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_api_proto_nebulapb_vector_service_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Vector) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type InsertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertRequest) Reset() {
	*x = InsertRequest{}
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertRequest) ProtoMessage() {}

func (x *InsertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertRequest.ProtoReflect.Descriptor instead.
func (*InsertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nebulapb_vector_service_proto_rawDescGZIP(), []int{1}
}

func (x *InsertRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type InsertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertResponse) Reset() {
	*x = InsertResponse{}
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResponse) ProtoMessage() {}

func (x *InsertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResponse.ProtoReflect.Descriptor instead.
func (*InsertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nebulapb_vector_service_proto_rawDescGZIP(), []int{2}
}

func (x *InsertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nebulapb_vector_service_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Matches       []*SearchResponse_Match `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nebulapb_vector_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetMatches() []*SearchResponse_Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type SearchResponse_Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse_Match) Reset() {
	*x = SearchResponse_Match{}
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse_Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse_Match) ProtoMessage() {}

func (x *SearchResponse_Match) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nebulapb_vector_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse_Match.ProtoReflect.Descriptor instead.
func (*SearchResponse_Match) Descriptor() ([]byte, []int) {
	return file_api_proto_nebulapb_vector_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *SearchResponse_Match) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchResponse_Match) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_proto_nebulapb_vector_service_proto protoreflect.FileDescriptor

const file_api_proto_nebulapb_vector_service_proto_rawDesc = "" +
	"\n" +
	"'api/proto/nebulapb/vector_service.proto\x12\bnebulapb\"0\n" +
	"\x06Vector\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06values\x18\x02 \x03(\x02R\x06values\"7\n" +
	"\rInsertRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\"@\n" +
	"\x0eInsertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\"y\n" +
	"\x0eSearchResponse\x128\n" +
	"\amatches\x18\x01 \x03(\v2\x1e.nebulapb.SearchResponse.MatchR\amatches\x1a-\n" +
	"\x05Match\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score2\x89\x01\n" +
	"\rVectorService\x12;\n" +
	"\x06Insert\x12\x17.nebulapb.InsertRequest\x1a\x18.nebulapb.InsertResponse\x12;\n" +
	"\x06Search\x12\x17.nebulapb.SearchRequest\x1a\x18.nebulapb.SearchResponseB5Z3github.com/sandeep89846/nebuladb/api/proto/nebulapbb\x06proto3"

var (
	file_api_proto_nebulapb_vector_service_proto_rawDescOnce sync.Once
	file_api_proto_nebulapb_vector_service_proto_rawDescData []byte
)

func file_api_proto_nebulapb_vector_service_proto_rawDescGZIP() []byte {
	file_api_proto_nebulapb_vector_service_proto_rawDescOnce.Do(func() {
		file_api_proto_nebulapb_vector_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_nebulapb_vector_service_proto_rawDesc), len(file_api_proto_nebulapb_vector_service_proto_rawDesc)))
	})
	return file_api_proto_nebulapb_vector_service_proto_rawDescData
}

var file_api_proto_nebulapb_vector_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_nebulapb_vector_service_proto_goTypes = []any{
	(*Vector)(nil),               // 0: nebulapb.Vector
	(*InsertRequest)(nil),        // 1: nebulapb.InsertRequest
	(*InsertResponse)(nil),       // 2: nebulapb.InsertResponse
	(*SearchRequest)(nil),        // 3: nebulapb.SearchRequest
	(*SearchResponse)(nil),       // 4: nebulapb.SearchResponse
	(*SearchResponse_Match)(nil), // 5: nebulapb.SearchResponse.Match
}
var file_api_proto_nebulapb_vector_service_proto_depIdxs = []int32{
	5, // 0: nebulapb.SearchResponse.matches:type_name -> nebulapb.SearchResponse.Match
	1, // 1: nebulapb.VectorService.Insert:input_type -> nebulapb.InsertRequest
	3, // 2: nebulapb.VectorService.Search:input_type -> nebulapb.SearchRequest
	2, // 3: nebulapb.VectorService.Insert:output_type -> nebulapb.InsertResponse
	4, // 4: nebulapb.VectorService.Search:output_type -> nebulapb.SearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_nebulapb_vector_service_proto_init() }
func file_api_proto_nebulapb_vector_service_proto_init() {
	if File_api_proto_nebulapb_vector_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_nebulapb_vector_service_proto_rawDesc), len(file_api_proto_nebulapb_vector_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_nebulapb_vector_service_proto_goTypes,
		DependencyIndexes: file_api_proto_nebulapb_vector_service_proto_depIdxs,
		MessageInfos:      file_api_proto_nebulapb_vector_service_proto_msgTypes,
	}.Build()
	File_api_proto_nebulapb_vector_service_proto = out.File
	file_api_proto_nebulapb_vector_service_proto_goTypes = nil
	file_api_proto_nebulapb_vector_service_proto_depIdxs = nil
}
